version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:13.7.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn run test
      - store_artifacts:
          path: coverage/clover.xml
          prefix: coverage
      - run:
          name: upload coverage report
          command: bash <(curl -s https://codecov.io/bash)
  build:
    docker:
      - image: circleci/node:13.7.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          path:
            - image.tar
      - run:
          name: Load Docker image cache
          command: 
            set +o pipefail
            docker load -i image.tar | true
      - run:
          name: Build Docker image
          command: docker build --cache-from=$IMAGE_NAME:latest -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - image.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    docker:
      - image: circleci/node:13.7.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker push $IMAGE_NAME:latest
  publish-tag:
    docker:
      - image: circleci/node:13.7.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_TAG
            docker push $IMAGE_NAME:$CIRCLE_TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
              branches:
                only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish-latest:
          context: DockerHub
          requires:
            - test
          filters:
            branches:
              only: master
  build-tags:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-tag:
          context: DockerHub
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  build-pulls:
    jobs:
      - build:
          filters:
            branches:
              only: /^pull.+/
      - test:
          requires:
            - build
          filters:
            branches:
              only: /^pull.+/